### ISSUE TITLE
need unified editor across interface

### ISSUE THREAD

**Issue by tylershuster** [urbit/indigo-react#89] opened 2020-12-18 03:42 UTC
**Problem**
Text editing behavior across Landscape is fragmented, exhibiting different characteristics between chat, notes, comments, et. al. Even markdown modes vary across implementations. Furthermore, some urbit-specific functionality such as `@p` autocomplete should exist but have regressed due to updates or swapping out implementations.

**Proposed Solution**
A unified, landscape-specific editor that can evolve with indigo's design language and will exhibit the same behavior across applications.

**Possible Alternatives**
Leaving things as they are, or finding a drop-in solution that isn't quite custom to landscape

**Additional context**
This issue serves as a sort of to-do reminder for myself as well as a thread for others to drop in resources that they should find. Design discussion should not occur on this thread, but technical implementations suggestions are welcome. I'll start:

https://remirror.io/

**Comment by matildepark** [comment] 2021-01-04 17:55
Ha, and duplicate of #66.

**Closed by matildepark** 2021-01-04 17:55 UTC
